/*
 * ============================================================================
 * FORM: MainForm (Logic)
 * ============================================================================
 * 
 * Main form of the AdventureWorks application.
 * Allows you to:
 * - Configure the database connection string
 * - Test the connection
 * - Navigate to the data management forms
 * 
 * TEACHING NOTE:
 * - This is the typical Windows Forms pattern: separation between
 *   design (*.Designer.cs) and logic (*.cs)
 * - The class is partial, shared between the two files
 * - Event handlers connect UI events to actions
 * ============================================================================
 */

using AdventureWorksApp.DataAccess;

namespace AdventureWorksApp.Forms
{
    /// <summary>
    /// Main form of the application.
    /// Manages database connection and navigation.
    /// </summary>
    public partial class MainForm : Form
    {
        /// <summary>
        /// Constructor of the main form.
        /// </summary>
        public MainForm()
        {
            InitializeComponent();
            
            // Event handler connections
            // NOTE: In a real project, these are generated by the designer
            this.Load += MainForm_Load;
            this.buttonTestConnection.Click += ButtonTestConnection_Click;
            this.buttonProducts.Click += ButtonProducts_Click;
            this.buttonSalesOrders.Click += ButtonSalesOrders_Click;
            this.buttonOrderDetails.Click += ButtonOrderDetails_Click;
        }

        /// <summary>
        /// Form load event.
        /// Initializes the UI with current values.
        /// </summary>
        private void MainForm_Load(object? sender, EventArgs e)
        {
            // If the connection string is already configured (from appsettings.json),
            // we display it in the textbox
            if (DbConnectionFactory.IsConfigured)
            {
                textBoxConnectionString.Text = DbConnectionFactory.ConnectionString;
                UpdateConnectionStatus("String loaded from configuration", Color.Blue);
            }
            
            // Enable navigation buttons only if connected
            UpdateNavigationButtons(DbConnectionFactory.IsConfigured);
        }

        /// <summary>
        /// Tests the database connection.
        /// 
        /// TEACHING NOTE:
        /// - We use async/await to not block the UI during the test
        /// - The method is async void because it's an event handler
        /// - We disable the button during the test to prevent multiple clicks
        /// </summary>
        private async void ButtonTestConnection_Click(object? sender, EventArgs e)
        {
            // Get the connection string from the textbox
            string connectionString = textBoxConnectionString.Text.Trim();
            
            if (string.IsNullOrWhiteSpace(connectionString))
            {
                UpdateConnectionStatus("Enter a valid connection string", Color.Red);
                return;
            }

            // Set the connection string
            DbConnectionFactory.ConnectionString = connectionString;

            // Disable the button during the test
            buttonTestConnection.Enabled = false;
            UpdateConnectionStatus("Testing...", Color.Orange);

            try
            {
                // Execute the async test
                var (success, message) = await DbConnectionFactory.TestConnectionAsync();

                if (success)
                {
                    UpdateConnectionStatus($"✓ {message}", Color.Green);
                    UpdateNavigationButtons(true);
                }
                else
                {
                    UpdateConnectionStatus($"✗ {message}", Color.Red);
                    UpdateNavigationButtons(false);
                }
            }
            catch (Exception ex)
            {
                UpdateConnectionStatus($"Error: {ex.Message}", Color.Red);
                UpdateNavigationButtons(false);
            }
            finally
            {
                // Re-enable the button
                buttonTestConnection.Enabled = true;
            }
        }

        /// <summary>
        /// Updates the displayed connection status.
        /// </summary>
        private void UpdateConnectionStatus(string message, Color color)
        {
            labelConnectionStatus.Text = $"Status: {message}";
            labelConnectionStatus.ForeColor = color;
        }

        /// <summary>
        /// Enables or disables navigation buttons.
        /// </summary>
        private void UpdateNavigationButtons(bool enabled)
        {
            buttonProducts.Enabled = enabled;
            buttonSalesOrders.Enabled = enabled;
            buttonOrderDetails.Enabled = enabled;
        }

        /// <summary>
        /// Opens the product management form.
        /// 
        /// TEACHING NOTE:
        /// - ShowDialog() opens the form modally (blocks the parent form)
        /// - Show() would open the form non-modally
        /// - For a teaching app, modal is simpler to manage
        /// </summary>
        private void ButtonProducts_Click(object? sender, EventArgs e)
        {
            using var productForm = new ProductForm();
            productForm.ShowDialog(this);
        }

        /// <summary>
        /// Opens the order management form.
        /// </summary>
        private void ButtonSalesOrders_Click(object? sender, EventArgs e)
        {
            using var ordersForm = new SalesOrderHeaderForm();
            ordersForm.ShowDialog(this);
        }

        /// <summary>
        /// Opens the order details management form.
        /// </summary>
        private void ButtonOrderDetails_Click(object? sender, EventArgs e)
        {
            using var detailsForm = new SalesOrderDetailForm();
            detailsForm.ShowDialog(this);
        }
    }
}
